5-1
htmlacademy-javascript/2290545-kekstagram-1 pull request #6
Opened 2023-08-22 19:51 UTC by apykhanov

123

2023-08-23 11:52 UTC, NikolayUsov commented on js/main.js
>  getPictures();
getPictures вернет массив моковых данных поэтому результат вызова функции желательно сохранить в переменную

2023-08-23 11:52 UTC, NikolayUsov commented on js/data.js
> +getPictures();
этот вызов тут не нужен

2023-08-23 11:52 UTC, NikolayUsov commented on js/data.js
> +  id: createIdGenerator(),
кажется тут у тебя ошибка createIdGenerator вернеи функцию которую если вызывать можно получить уникальный айди

см пример с generatedCommentId

2023-08-29 17:53 UTC, ekazakov requested changes

2023-08-29 17:53 UTC, ekazakov commented on index.html
> +  <script src="js/main.js" type="modul"></script>
Опечатка в слове `module` — из-за нее браузер не загружает файл

2023-08-29 17:53 UTC, ekazakov commented on js/data.js
> +const generatedCommentId = createIdGenerator ();
`generatedCommentId` — правильнее назвать `generateCommentId`

2023-08-29 17:53 UTC, ekazakov commented on js/data.js
> +  id: createIdGenerator(),
Да, тут ошибка. Тебе надо сперва по аналогии с тем как на 22й строке сделать.
`createIdGenerator` — возвращает ф-ю. Тебе надо эту ф-ю сохранить в переменную и затем уже вызывать для генерации id картики.

2023-08-29 17:53 UTC, ekazakov commented on js/main.js
> +import { getPictures } from './data';
Тут потерялся тип файла у `./data` — надо `./data.js`. Без типа браузер файл загружать не будет.

 Еще стоит для отладки добавить: 
 
 ```
 console.log('pictures:', getPictures());
 ```
 
 Так сможешь увидеть какие объекты создаются

2023-08-30 06:11 UTC, ekazakov commented on js/data.js
> +console.log('pictures:', getPictures());
Перенеси в main.js

2023-08-30 06:17 UTC, merged